github: [RaenonX]
patreon: RaenonX
custom:
  - 'https://pks.raenonx.cc/en/docs/view/subscription/intro'
  - 'https://ptcgp.raenonx.cc/en/docs/view/subscription/intro'
  - 'https://discord.gg/eeveesleep'
